tap "charmbracelet/tap"
tap "coursier/formulas"
tap "derailed/k9s"
tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "instrumenta/instrumenta"
tap "koekeishiya/formulae"
tap "remotemobprogramming/brew"
tap "spotify/public"
tap "spotify/sptaps", "git@ghe.spotify.net:shared/homebrew-spotify.git"
tap "virtuslab/git-machete"
tap "weaveworks/tap"
tap "ykursadkaya/openlens"
# Slice and dice log files on the command-line
brew "angle-grinder"
# Image format providing lossless and lossy compression for web images
brew "webp"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Generic library support script
brew "libtool"
# YAML Parser
brew "libyaml"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Terminal bandwidth utilization tool
brew "bandwhich"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Core application library for C
brew "glib"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Cross-platform make
brew "cmake"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Utility that creates projects from templates
brew "cookiecutter"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Diff that understands syntax
brew "difftastic"
# Load/unload environment variables based on $PWD
brew "direnv"
# Lightweight DNS forwarder and DHCP server
brew "dnsmasq"
# Bash, Zsh and Fish completion for Docker
brew "docker-completion"
# Replay stored shell commands for live presentations
brew "doitlive"
# CLI tool for running SQL queries against JSON, CSV, Excel, Parquet, and more
brew "dsq"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Command-line fuzzy finder written in Go
brew "fzf"
# Library for encoding and decoding .avif files
brew "libavif"
# Graphics library to dynamically manipulate images
brew "gd"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Git repository organizer & rebase workflow automation tool
brew "git-machete"
# Declarative configuration for Gmail filters
brew "gmailctl"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU version of the tar archiving utility
brew "gnu-tar"
# International domain name library (IDNA2008, Punycode and TR46)
brew "libidn2"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Go programming environment (1.17)
brew "go@1.17"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Image manipulation
brew "netpbm"
# OpenType text shaping engine
brew "harfbuzz"
# Framework for layout and rendering of i18n text
brew "pango"
# Library to render SVG files using Cairo
brew "librsvg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# GNU grep, egrep and fgrep
brew "grep"
# Like cURL, but for gRPC
brew "grpcurl"
# Kubernetes package manager
brew "helm"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Modern alternative to the watch command
brew "hwatch"
# International Ispell
brew "ispell"
# Manage your Java environment
brew "jenv"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Run local Kubernetes cluster in Docker
brew "kind"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Kubernetes controller and tool for one-way encrypted Secrets
brew "kubeseal"
# Validate Kubernetes configuration files, supports multiple Kubernetes versions
brew "kubeval"
# Template-free customization of Kubernetes YAML manifests
brew "kustomize"
# C library SSHv1/SSHv2 client and server protocols
brew "libssh"
# Mac App Store command-line interface
brew "mas"
# Java-based project management
brew "maven"
# Program for MPEG audio stream validation
brew "mp3val"
# Check MP3 files for errors
brew "mpck"
# Command-line interface for New Relic
brew "newrelic-cli"
# HTTP/2 C Library
brew "nghttp2"
# Manage multiple Node.js versions
brew "nvm"
# Pretty-print tabular data in Python
brew "python-tabulate"
# CLI for Postgres with auto-completion and syntax highlighting
brew "pgcli"
# Object-relational database system
brew "postgresql@14"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Python version management
brew "pyenv"
# Persistent key-value database, with built-in net interface
brew "redis"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Build tool for Scala projects
brew "sbt"
# JVM-based programming language
brew "scala"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Cross-shell prompt for astronauts
brew "starship"
# Tail multiple Kubernetes pods & their containers
brew "stern"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Send macOS User Notifications from the command-line
brew "terminal-notifier"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# HTTP load testing tool and library
brew "vegeta"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Friendly and fast tool for sending HTTP requests
brew "xh"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# General-purpose lossless data-compression library
brew "zlib"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# A tool for glamorous shell scripts
brew "charmbracelet/tap/gum"
# Launcher for Coursier
brew "coursier/formulas/coursier"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "derailed/k9s/k9s"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
# Simple hotkey-daemon for macOS.
brew "koekeishiya/formulae/skhd"
# Swift handover for remote mobs using git. mob is a CLI tool written in GO. It keeps your master branch clean and creates WIP commits on mob-session branch.
brew "remotemobprogramming/brew/mob"
# Scala API for Apache Beam and Google Cloud Dataflow
brew "spotify/public/scio"
# Hades CLI utility
brew "spotify/sptaps/hades-cli"
brew "spotify/sptaps/hmtools"
brew "spotify/sptaps/kubectl-site"
# Protoman is used to fetch protobuf schemas from our central ghe.spotify.net/shared/proto repository
brew "spotify/sptaps/protoman"
brew "spotify/sptaps/styx-cli"
# The official CLI for Amazon EKS
brew "weaveworks/tap/eksctl"
# Command-line helper for the 1Password password manager
cask "1password-cli"
# GPU-accelerated terminal emulator
cask "alacritty"
# Automatic tiling window manager similar to xmonad
cask "amethyst"
# Menu bar status indicator
cask "anybar"
# Compact TeX distribution as alternative to the full TeX Live / MacTeX
cask "basictex"
# OpenJDK distribution from Amazon
cask "corretto11"
# OpenJDK distribution from Amazon
cask "corretto8"
# App to build and share containerized applications and microservices
cask "docker"
# Tool to hide status bar icons
cask "dozer"
# Text editor
cask "emacs"
# Utility for customizing which browser to start
cask "finicky"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Menu bar calendar
cask "itsycal"
# Open source build of Lens Kubernetes IDE
cask "openlens"
# App that enables mouse-free UI interaction
cask "shortcat"
# Daily planner and calendar
cask "sunsama"
# Virtualizer for x86 hardware
cask "virtualbox"
# Network protocol analyzer
cask "wireshark"
mas "Amphetamine", id: 937984704
mas "Booklet", id: 1375737884
mas "Clocker", id: 1056643111
mas "Endel", id: 1484348796
mas "GarageBand", id: 682658836
mas "Gestimer", id: 990588172
mas "HazeOver", id: 430798174
mas "iMovie", id: 408981434
mas "Instapaper", id: 288545208
mas "InYourFace", id: 1476964367
mas "Keynote", id: 409183694
mas "MeetingBar", id: 1532419400
mas "Micro Snitch", id: 972028355
mas "Mob Timer", id: 1594924856
mas "Monodraw", id: 920404675
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
