
[appearance]
mode = "dark"

[borders]
enabled = true
width = 5.0

[borders.color]
alpha = 1.0
blue = 0.979300037944676
green = 1.0
red = 0.08458520228437894

[focus]
followsMouse = false
followsWindowToMonitor = false
moveMouseToFocusedWindow = false

[gaps]
size = 16.0

[gaps.outer]
bottom = 0.0
left = 0.0
right = 0.0
top = 0.0

[general]
developerModeEnabled = false
hotkeysEnabled = true
ipcEnabled = false
preventSleepEnabled = false

[gestures]
fingerCount = 3
invertDirection = true
mouseResizeModifierKey = "option"
scrollEnabled = true
scrollModifierKey = "optionShift"
scrollSensitivity = 5.0

[mouseWarp]
axis = "horizontal"
margin = 1
monitorOrder = []

[niri]
balancedColumnCount = 2
columnWidthPresets = [0.35, 0.5, 0.65, 0.95]
infiniteLoop = false
revealPartial = "default"

[statusBar]
showAppNames = false
showWorkspaceName = false
useWorkspaceId = false

[workspaceBar]
backgroundOpacity = 0.01
deduplicateAppIcons = false
enabled = false
height = 24.0
hideEmptyWorkspaces = true
labelFontSize = 12.0
notchAware = true
position = "overlappingMenuBar"
reserveLayoutSpace = true
showFloatingWindows = false
showLabels = true
showTraceButton = false
windowLevel = "popup"
xOffset = -500.0
yOffset = 10.0
