# Use tall and fullscreen layouts
layouts:
  - tall
  - fullscreen
  - tall-right
  - wide
  - two-pane
  - 3column-left
  - middle-wide
  - 3column-right
  - 4column-left
  - 4column-right
  - column
  - row
  - floating
  - widescreen-tall
  - widescreen-tall-right
  - bsp

# Add "command" to the default mods
mod1:
  - option
  - shift

mod2:
  - option
  - shift
  - control

# Move in increments of 5px when resizing windows
window-resize-step: 5;

# When enabled margins will not be applied to fullscreen layout or when there is only on window
smart-window-margins: false

window-minimum-height: 0
window-minimum-width: 0

ignore-menu-bar: false
disable-padding-on-builtin-display: false

float-small-windows: true

# Mouse
mouse-follows-focus: true
focus-follows-mouse: false

# HUD
enables-layout-hud: true
enables-layout-hud-on-space-change: true

## Windows
new-windows-to-main: false
follow-space-thrown-windows: true

# Add 15px margin between windows
window-margins: true

# window-margin-size: 72.811
# screen-padding-left: 72.811
# screen-padding-right: 72.811
# screen-padding-top: 45
# screen-padding-bottom: 45

window-margin-size: 15
screen-padding-left: 0
screen-padding-right: 0
screen-padding-top: 0
screen-padding-bottom: 9.2

# Modify the amethyst relaunch to use x and not z
relaunch-amethyst:
  mod: mod2
  key: z
cycle-layout:
  mod: mod1
  key: space
cycle-layout-backward:
  mod: mod2
  key: space
shrink-main:
  mod: mod1
  key: h
expand-main:
  mod: mod1
  key: l
increase-main:
  mod: mod1
  key: =
decrease-main:
  mod: mod1
  key: "-"
focus-ccw:
  mod: mod1
  key: k
focus-cw:
  mod: mod1
  key: j
focus-main:
  mod: mod1
  key: m
focus-screen-ccw:
  mod: mod1
  key: p
focus-screen-cw:
  mod: mod1
  key: n
swap-screen-ccw:
  mod: mod2
  key: p
swap-screen-cw:
  mod: mod2
  key: n
swap-ccw:
  mod: mod2
  key: k
swap-cw:
  mod: mod2
  key: j
swap-main:
  mod: mod2
  key: enter
focus-screen-1:
  mod: mod1
  key: w
focus-screen-2:
  mod: mod1
  key: e
throw-screen-1:
  mod: mod2
  key: w
throw-screen-2:
  mod: mod2
  key: e
throw-space-left:
  mod: mod2
  key: left
throw-space-right:
  mod: mod2
  key: right
toggle-tiling:
  mod: mod2
  key: t
toggle-float:
  mod: mod1
  key: t

select-tall-layout:
  mod: mod1
  key: a
select-wide-layout:
  mod: mod1
  key: s
select-fullscreen-layout:
  mod: mod1
  key: f
select-column-layout:
  mod: mod1
  key: c
select-two-pane-layout:
  mod: mod1
  key: d
select-row-layout:
  mod: mod1
  key: r
select-bsp-layout:
  mod: mod1
  key: b
reevaluate-windows:
  mod: mod1
  key: z
