format = """\
    $time $cmd_duration\
    $line_break\
    $line_break\
    $username\
    $hostname\
    $directory\
    $kubernetes\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $docker_context\
    $package\
    $dotnet\
    $elixir\
    $elm\
    $erlang\
    $golang\
    $java\
    $julia\
    $nim\
    $nodejs\
    $ocaml\
    $php\
    $purescript\
    $python\
    $ruby\
    $rust\
    $terraform\
    $zig\
    $nix_shell\
    $conda\
    $memory_usage\
    $aws\
    $env_var\
    $crystal\
    $custom\
    $line_break\
    $jobs\
    $battery\
    $character\
"""

add_newline=false

[kubernetes]
disabled = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "

[time]
format = "[completed at](purple) [$time]($style)"
disabled = false

[git_status]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[aws]
disabled = true

[cmd_duration]
format = "[took](purple) [$duration]($style)"
show_notifications = true
min_time_to_notify = 10_000
