format = """\
    $cmd_duration\
    $line_break\
    $line_break\
    ($gcloud\n)\
    ($kubernetes\n)\
    ($direnv\n)\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $docker_context\
    $package\
    $golang\
    $nodejs\
    $python\
    $rust\
    $terraform\
    $zig\
    $nix_shell\
    $memory_usage\
    $env_var\
    $custom\
    $line_break\
    $jobs\
    $battery\
    $character\
"""

add_newline=false

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style)'

[kubernetes.context_aliases]
"gke_pryon-mainline-e2e-1_us-central1_api-deployment-warrenharper-k8s" = "mainline-warrenharper-k8s"


[directory]
format = "[$path]($style)[$read_only]($read_only_style) "

[direnv]
disabled = false
symbol = "\ue5fc "

[time]
format = "(purple)[$time]($style)"
disabled = false

[git_status]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[aws]
disabled = true
format = '[$symbol($profile )(\($region\) )(\[$duration\])]($style)'
symbol = "🅰 "

[gcloud]
disabled = false
format = '[$symbol$account(@$domain)(\($project)(:$region)\)]($style)'
symbol = "☁ "

[cmd_duration]
format = "[took](purple) [$duration]($style)"
min_time = 1
show_notifications = false
min_time_to_notify = 10_000

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red)'
