format = """
([](#FCA17D)[$cmd_duration](fg:#DA627D bg:#FCA17D)[](#FCA17D))

[](#DA627D)$directory[](fg:#DA627D bg:#FCA17D)\
$git_branch$git_status[](fg:#FCA17D)\
(\n[](fg:#33658A)$direnv[](fg:#33658A))\
\n$character\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = '[ ❯](bold green)'
error_symbol = '[ ✗](bold red)'

[cmd_duration]
format = 'took [$duration]($style)'
style = "bg:#FCA17D"

[directory]
style = "bg:#DA627D"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[direnv]
disabled = false
symbol = "\ue5fc "
style = "bg:#33658A"
format = '[$symbol$loaded/$allowed]($style)'

[gcloud]
disabled = false
format = '[$symbol$account(@$domain)(\($project)(:$region)\)]($style)'
symbol = "☁ "

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style)'
[kubernetes.context_aliases]
"gke_pryon-mainline-e2e-1_us-central1_api-deployment-warrenharper-k8s" = "mainline-warrenharper-k8s"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#9A348E"
format = '[](#9A348E)[started at $time]($style)[](#9A348E)'
